# Generated by Django 4.1.3 on 2022-11-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeacion', '0005_alter_tip_tramites_id_tramite'),
    ]

    operations = [
        migrations.CreateModel(
            name='tramites_sec',
            fields=[
                ('id_tramite_sec', models.AutoField(primary_key=True, serialize=False)),
                ('id_tramite_tip', models.CharField(max_length=50)),
                ('tip_tramites_tip', models.CharField(max_length=100)),
                ('nombre_solic', models.CharField(max_length=100)),
                ('num_ide_solic', models.CharField(max_length=100)),
                ('contacto_solic', models.CharField(max_length=100)),
                ('correo_solic', models.CharField(max_length=100)),
                ('fecha_solic', models.DateField()),
                ('estado_solic', models.CharField(max_length=100)),
                ('observacion_solic', models.CharField(max_length=100)),
                ('documento_solic', models.CharField(max_length=100)),
            ],
        ),
    ]
