# Generated by Django 4.1.3 on 2022-11-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeacion', '0006_tramites_sec'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramites_sec',
            name='nombre_tramite_sec',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
