# Generated by Django 4.1.3 on 2022-12-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeacion', '0007_tramites_sec_nombre_tramite_sec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramites_sec',
            name='documento_solic',
            field=models.FileField(upload_to=''),
        ),
    ]
